/** You must provide a log_strings_app.h file containing the strings
 * that match your application's log events.  This is a sample of the format.
 * It must be kept in line with the strings in log_enum_app.h.
 */
    "  PROTOCOL_VERSION",
    "  SYSTEM_VERSION",
    "* POST_ERROR",
    "  POST_BEST_EFFORT",
    "* BME280_ERROR",
    "  WAKE_UP",
    "  POWER",
    "  MODEM_TYPE",
    "  ACTION",
    "  ACTION_ALLOC_FAILURE",
    "  ACTION_THREAD_ALLOC_FAILURE",
    "  ACTION_THREAD_STARTED",
    "* ACTION_THREAD_START_FAILURE",
    "  ACTION_THREAD_TERMINATED",
    "  ACTION_THREAD_SIGNALLED",
    "  ACTION_THREADS_RUNNING",
    "* ACTION_DRIVER_INIT_FAILURE",
    "* ACTION_DRIVER_HEAP_TOO_LOW",
    "  TIME_SET",
    "* GET_IMEI_FAILURE",
    "* CONNECT_FAILURE",
    "* GET_TIME_FAILURE",
    "  ALL_THREADS_TERMINATED",
    "  DATA_ITEM_ALLOC",
    "* DATA_ITEM_ALLOC_FAILURE",
    "  DATA_ITEM_FREE",
    "  PROCESSOR_FINISHED",
    "  V_BAT_OK_READING_MV",
    "  V_IN_READING_MV",
    "  V_PRIMARY_READING_MV"
